/**
 * Book details actions types constants.
 */

export const CREATE_NEW_BOOK = 'CREATE_NEW_BOOK';
export const DELETE_BOOK = 'DELETE_BOOK';
export const DETAILS_LOADING_START = 'DETAILS_LOADING_START';
export const DETAILS_LOADING_SUCCESS = 'DETAILS_LOADING_SUCCESS';
export const DETAILS_LOADING_ERROR = 'DETAILS_LOADING_ERROR';
export const UPDATE_BOOK_STATUS = 'UPDATE_BOOK_STATUS';
